apiVersion: v1
kind: ConfigMap
metadata:
  name: dbinit-configmap
  namespace: proj1
data:
  0_init.sql: |
    CREATE DATABASE IF NOT EXISTS patientsdb;

    USE patientsdb;

    DROP TABLE IF EXISTS patients;

    CREATE TABLE patients (
      id         BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
      full_name VARCHAR(255) DEFAULT NULL,
      phone      VARCHAR(255) DEFAULT NULL,
       age      VARCHAR(255) DEFAULT NULL,
      address    VARCHAR(255) DEFAULT NULL,
      gender  VARCHAR(255) DEFAULT NULL,
      prescription  VARCHAR(255) DEFAULT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (id),
      CONSTRAINT UQ_Patients_Email UNIQUE (email)
    );

    DELIMITER //
    CREATE PROCEDURE create_and_return(IN full_name VARCHAR(255) DEFAULT NULL,
                     IN phone VARCHAR(255), IN address VARCHAR(255), IN gender VARCHAR(255),
                      IN  prescription VARCHAR(255))
    BEGIN
      INSERT INTO patients( full_name , phone, address, gender,  prescription) VALUES ( full_name, phone, address, gender,prescription);

      SET @PATIENT_ID = LAST_INSERT_ID();

      SELECT * FROM patients WHERE id=@PATIENT_ID;
    END //
    DELIMITER ;
