apiVersion: v1
kind: Service
metadata:
  name: mysqldb-service
  namespace: proj-no-secrets
spec:
  selector:
    app: mysqldb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP