apiVersion: v1
kind: Service
metadata:
  name: pythonapp-service
  namespace: proj-no-secrets
spec:
  selector:
    app: pythonapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer