apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonapp-deployment
  namespace: proj-no-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythonapp
  template:
    metadata:
      labels:
        app: pythonapp
    spec:
      containers:
      - name: pythonapp
        image: savitha2789/flask-mysql
        env:
        - name: DB_HOST
          value: mysqldb-service
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: admin
        - name: DB_PASSWORD
          value: password
        - name: DB_NAME
          value: patientsdb
        ports:
        - containerPort: 5000
