apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01
  namespace: proj-no-secrets
spec:
  storageClassName: db
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/pv01/