apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: proj-no-secrets
spec:
  storageClassName: db
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Specify the size you need